// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2aW-SW1ZdrV_XYFInM0FPZtqABjU4YaQ',
    appId: '1:403203235877:web:e5642d4ad6e9c83a9ddfcc',
    messagingSenderId: '403203235877',
    projectId: 'flutter-coding-task',
    authDomain: 'flutter-coding-task.firebaseapp.com',
    storageBucket: 'flutter-coding-task.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZJqV8qjHT5rJSGvDNeL0QvpscQ5e59ME',
    appId: '1:403203235877:android:a530fc5a112f89379ddfcc',
    messagingSenderId: '403203235877',
    projectId: 'flutter-coding-task',
    storageBucket: 'flutter-coding-task.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3NP5I1dHVJLm64DSoOqsn01nbaSlBX20',
    appId: '1:403203235877:ios:b3fa9f8e1c462e279ddfcc',
    messagingSenderId: '403203235877',
    projectId: 'flutter-coding-task',
    storageBucket: 'flutter-coding-task.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3NP5I1dHVJLm64DSoOqsn01nbaSlBX20',
    appId: '1:403203235877:ios:b3fa9f8e1c462e279ddfcc',
    messagingSenderId: '403203235877',
    projectId: 'flutter-coding-task',
    storageBucket: 'flutter-coding-task.appspot.com',
    iosBundleId: 'com.example.codingTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2aW-SW1ZdrV_XYFInM0FPZtqABjU4YaQ',
    appId: '1:403203235877:web:545a9b12539c39179ddfcc',
    messagingSenderId: '403203235877',
    projectId: 'flutter-coding-task',
    authDomain: 'flutter-coding-task.firebaseapp.com',
    storageBucket: 'flutter-coding-task.appspot.com',
  );
}
